
# Docker Compose pour l'environnement de DÉVELOPPEMENT LOCAL
# Ce fichier démarre tous les services Meeshy en local avec les dernières images Docker
# URLs d'accès:
#   - Frontend: http://localhost:3100
#   - Gateway API: http://localhost:3000
#   - Translator API: http://localhost:8000
#   - MongoDB: mongodb://localhost:27017
#   - Redis: redis://localhost:6379
#   - NoSQLClient (MongoDB UI): http://localhost:3001
#   - P3X Redis UI: http://localhost:7843

services:
  # Base de données MongoDB avec Replica Set
  database:
    image: mongo:latest
    platform: linux/arm64
    container_name: meeshy-dev-database
    restart: unless-stopped
    command: mongod --replSet rs0 --bind_ip_all --noauth
    environment:
      MONGO_INITDB_DATABASE: ${MONGODB_DATABASE:-meeshy}
    ports:
      - "27017:27017"
    volumes:
      - dev_database_data:/data/db
      - dev_database_config:/data/configdb
      - ./shared/init-mongodb-replica.sh:/docker-entrypoint-initdb.d/init-mongodb-replica.sh:ro
      - ./shared/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - meeshy-dev-network
    healthcheck:
      test: ["CMD-SHELL", "echo 'db.runCommand(\"ping\").ok' | mongosh mongodb://localhost:27017/${MONGODB_DATABASE:-meeshy} --quiet || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # NoSQLClient - Interface MongoDB
  nosqlclient:
    image: mongoclient/mongoclient:latest
    container_name: meeshy-dev-nosqlclient
    restart: unless-stopped
    environment:
      MONGOCLIENT_DEFAULT_CONNECTION_URL: "mongodb://database:27017/${MONGODB_DATABASE:-meeshy}?replicaSet=rs0&directConnection=true"
      ROOT_URL: "http://localhost:3001"
      PORT: 3000
    ports:
      - "3001:3000"
    depends_on:
      database:
        condition: service_healthy
    networks:
      - meeshy-dev-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # Cache Redis  
  redis:
    image: redis:8-alpine
    container_name: meeshy-dev-redis
    restart: unless-stopped
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - dev_redis_data:/data
    networks:
      - meeshy-dev-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # P3X Redis UI - Interface Redis
  p3x-redis-ui:
    image: patrikx3/p3x-redis-ui:latest
    container_name: meeshy-dev-p3x-redis-ui
    restart: unless-stopped
    environment:
      - P3X_REDIS_UI_SETTINGS={"hostname":"redis","port":6379,"password":"","meeshy-dev-database":0}
      - P3X_REDIS_UI_HTTP_PORT=7843
      - P3XRS_SETTINGS_PATH=/settings
    ports:
      - "7843:7843"
    volumes:
      - dev_redis_ui_data:/settings
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - meeshy-dev-network
    healthcheck:
      test: ["CMD-SHELL", "netstat -an | grep :7843 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # Translator Service - Service de traduction ML
  translator:
    image: ${TRANSLATOR_IMAGE:-isopen/meeshy-translator:latest}
    platform: linux/arm64
    container_name: meeshy-dev-translator
    restart: unless-stopped
    environment:
      - DATABASE_TYPE=${DATABASE_TYPE:-MONGODB}
      - DATABASE_URL=${DATABASE_URL:-mongodb://meeshy-dev-database:27017/meeshy}
      - PRISMA_SCHEMA_PATH=${PRISMA_SCHEMA_PATH}
      - PYTHONPATH=/workspace:/workspace/generated
      - PYTHONUNBUFFERED=1
      - NODE_ENV=development
      - HF_HOME=/workspace/models
      - TRANSFORMERS_CACHE=/workspace/models
      - HUGGINGFACE_HUB_CACHE=/workspace/models
    ports:
      - "8000:8000"
    volumes:
      - dev_models_data:/workspace/models
    depends_on:
      database:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - meeshy-dev-network
    healthcheck:
      test: ["CMD", "python3", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/health')"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  # Gateway Service - API Gateway et WebSocket
  gateway:
    image: ${GATEWAY_IMAGE:-isopen/meeshy-gateway:latest}
    platform: linux/arm64
    container_name: meeshy-dev-gateway
    restart: unless-stopped
    environment:
      - DATABASE_TYPE=${DATABASE_TYPE:-MONGODB}
      - DATABASE_URL=${DATABASE_URL:-mongodb://meeshy-dev-database:27017/meeshy}
      - REDIS_URL=redis://redis:6379
      - TRANSLATOR_URL=http://translator:8000
      - ZMQ_PUSH_URL=tcp://translator:5555
      - ZMQ_SUB_URL=tcp://translator:5558
      - ZMQ_TRANSLATOR_HOST=translator
      - ZMQ_TRANSLATOR_PUSH_PORT=5555
      - ZMQ_TRANSLATOR_SUB_PORT=5558
      - NODE_ENV=development
      - CORS_ORIGINS=${CORS_ORIGINS:-http://localhost:3100}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS:-http://localhost:3100}
      - FRONTEND_URL=${FRONTEND_URL:-http://localhost:3100}
      - JWT_SECRET=${JWT_SECRET:-dev-jwt-secret-change-in-production}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN:-7d}
      # Variables d'initialisation des utilisateurs
      - FORCE_DB_RESET=${FORCE_DB_RESET:-false}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin123}
      - MEESHY_PASSWORD=${MEESHY_PASSWORD:-meeshy123}
      - ATABETH_PASSWORD=${ATABETH_PASSWORD:-atabeth123}
      - ADMIN_EMAIL=${ADMIN_EMAIL:-admin@meeshy.local}
      - MEESHY_EMAIL=${MEESHY_EMAIL:-meeshy@meeshy.local}
      - ATABETH_EMAIL=${ATABETH_EMAIL:-atabeth@meeshy.local}
      - ADMIN_SYSTEM_LANGUAGE=${ADMIN_SYSTEM_LANGUAGE:-fr}
      - ADMIN_REGIONAL_LANGUAGE=${ADMIN_REGIONAL_LANGUAGE:-fr}
      - ADMIN_CUSTOM_DESTINATION_LANGUAGE=${ADMIN_CUSTOM_DESTINATION_LANGUAGE}
      - MEESHY_SYSTEM_LANGUAGE=${MEESHY_SYSTEM_LANGUAGE:-en}
      - MEESHY_REGIONAL_LANGUAGE=${MEESHY_REGIONAL_LANGUAGE:-en}
      - MEESHY_CUSTOM_DESTINATION_LANGUAGE=${MEESHY_CUSTOM_DESTINATION_LANGUAGE}
      - ATABETH_USERNAME=${ATABETH_USERNAME:-atabeth}
      - ATABETH_FIRST_NAME=${ATABETH_FIRST_NAME:-Atabeth}
      - ATABETH_LAST_NAME=${ATABETH_LAST_NAME:-Meeshy}
      - ATABETH_ROLE=${ATABETH_ROLE:-user}
      - ATABETH_SYSTEM_LANGUAGE=${ATABETH_SYSTEM_LANGUAGE:-es}
      - ATABETH_REGIONAL_LANGUAGE=${ATABETH_REGIONAL_LANGUAGE:-es}
      - ATABETH_CUSTOM_DESTINATION_LANGUAGE=${ATABETH_CUSTOM_DESTINATION_LANGUAGE}
    ports:
      - "3000:3000"
    depends_on:
      database:
        condition: service_healthy
      redis:
        condition: service_healthy
      translator:
        condition: service_healthy
    networks:
      - meeshy-dev-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # Frontend Service - Interface utilisateur Next.js
  frontend:
    image: ${FRONTEND_IMAGE:-isopen/meeshy-frontend:latest}
    platform: linux/arm64
    container_name: meeshy-dev-frontend
    restart: unless-stopped
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:3000
      - NEXT_PUBLIC_WS_URL=ws://localhost:3000
      - NEXT_PUBLIC_TRANSLATION_URL=http://localhost:8000/translate
      - NEXT_PUBLIC_BACKEND_URL=http://localhost:3000
      - NEXT_PUBLIC_FRONTEND_URL=http://localhost:3100
      - NEXT_PUBLIC_DISABLE_CLIENT_TRANSLATION=${NEXT_PUBLIC_DISABLE_CLIENT_TRANSLATION:-true}
      - NEXT_PUBLIC_USE_API_TRANSLATION_ONLY=${NEXT_PUBLIC_USE_API_TRANSLATION_ONLY:-true}
      - NEXT_PUBLIC_DEBUG_LOGS=${NEXT_PUBLIC_DEBUG_LOGS:-true}
      - NODE_ENV=development
    ports:
      - "3100:3100"
    depends_on:
      gateway:
        condition: service_healthy
    networks:
      - meeshy-dev-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://0.0.0.0:3100"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

networks:
  meeshy-dev-network:
    driver: bridge
    name: meeshy-dev-network

volumes:
  dev_database_data:
    name: meeshy-dev-database-data
  dev_database_config:
    name: meeshy-dev-database-config
  dev_redis_data:
    name: meeshy-dev-redis-data
  dev_redis_ui_data:
    name: meeshy-dev-redis-ui-data
  dev_models_data:
    name: meeshy-dev-models-data
