version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: meeshy-postgres
    environment:
      POSTGRES_DB: meeshy
      POSTGRES_USER: meeshy
      POSTGRES_PASSWORD: MeeshyP@ssword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U meeshy -d meeshy"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - meeshy-network

  redis:
    image: redis:7-alpine
    container_name: meeshy-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - meeshy-network

  meeshy:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_VERSION: 22
        PNPM_VERSION: 8.15.0
    container_name: meeshy-app
    ports:
      - "3100:3100"  # Frontend
      - "3000:3000"  # Gateway
      - "8000:8000"  # Translator
    environment:
      - USE_EXTERNAL_DB=true
      - START_POSTGRES=false
      - START_REDIS=false
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DATABASE_URL=postgresql://meeshy:MeeshyP@ssword@postgres:5432/meeshy
      - REDIS_URL=redis://redis:6379
    env_file:
      - env.docker
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - meeshy-network
    restart: unless-stopped

networks:
  meeshy-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
