packages:
  - 'frontend'
  - 'gateway'
  - 'translator'
  - 'shared'
  - 'packages/mls-core'

ignoredBuiltDependencies:
  - '@tensorflow/tfjs-node'
  - core-js
  - onnxruntime-node
  - protobufjs
  - sharp
  - unrs-resolver

onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - esbuild
  - prisma
