# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import translation_pb2 as translation__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in translation_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TranslationServiceStub(object):
    """Service de traduction principal
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.TranslateText = channel.unary_unary(
                '/translation.TranslationService/TranslateText',
                request_serializer=translation__pb2.TranslateRequest.SerializeToString,
                response_deserializer=translation__pb2.TranslateResponse.FromString,
                _registered_method=True)
        self.TranslateMultiple = channel.unary_unary(
                '/translation.TranslationService/TranslateMultiple',
                request_serializer=translation__pb2.TranslateMultipleRequest.SerializeToString,
                response_deserializer=translation__pb2.TranslateMultipleResponse.FromString,
                _registered_method=True)
        self.DetectLanguage = channel.unary_unary(
                '/translation.TranslationService/DetectLanguage',
                request_serializer=translation__pb2.DetectLanguageRequest.SerializeToString,
                response_deserializer=translation__pb2.DetectLanguageResponse.FromString,
                _registered_method=True)
        self.GetSupportedLanguages = channel.unary_unary(
                '/translation.TranslationService/GetSupportedLanguages',
                request_serializer=translation__pb2.SupportedLanguagesRequest.SerializeToString,
                response_deserializer=translation__pb2.SupportedLanguagesResponse.FromString,
                _registered_method=True)
        self.GetServiceStats = channel.unary_unary(
                '/translation.TranslationService/GetServiceStats',
                request_serializer=translation__pb2.ServiceStatsRequest.SerializeToString,
                response_deserializer=translation__pb2.ServiceStatsResponse.FromString,
                _registered_method=True)


class TranslationServiceServicer(object):
    """Service de traduction principal
    """

    def TranslateText(self, request, context):
        """Traduction simple vers une langue
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TranslateMultiple(self, request, context):
        """Traduction vers plusieurs langues en parallèle
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DetectLanguage(self, request, context):
        """Détection de langue avec analyse de complexité
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSupportedLanguages(self, request, context):
        """Liste des langues supportées
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetServiceStats(self, request, context):
        """Statistiques du service
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TranslationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'TranslateText': grpc.unary_unary_rpc_method_handler(
                    servicer.TranslateText,
                    request_deserializer=translation__pb2.TranslateRequest.FromString,
                    response_serializer=translation__pb2.TranslateResponse.SerializeToString,
            ),
            'TranslateMultiple': grpc.unary_unary_rpc_method_handler(
                    servicer.TranslateMultiple,
                    request_deserializer=translation__pb2.TranslateMultipleRequest.FromString,
                    response_serializer=translation__pb2.TranslateMultipleResponse.SerializeToString,
            ),
            'DetectLanguage': grpc.unary_unary_rpc_method_handler(
                    servicer.DetectLanguage,
                    request_deserializer=translation__pb2.DetectLanguageRequest.FromString,
                    response_serializer=translation__pb2.DetectLanguageResponse.SerializeToString,
            ),
            'GetSupportedLanguages': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSupportedLanguages,
                    request_deserializer=translation__pb2.SupportedLanguagesRequest.FromString,
                    response_serializer=translation__pb2.SupportedLanguagesResponse.SerializeToString,
            ),
            'GetServiceStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetServiceStats,
                    request_deserializer=translation__pb2.ServiceStatsRequest.FromString,
                    response_serializer=translation__pb2.ServiceStatsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'translation.TranslationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('translation.TranslationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TranslationService(object):
    """Service de traduction principal
    """

    @staticmethod
    def TranslateText(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/translation.TranslationService/TranslateText',
            translation__pb2.TranslateRequest.SerializeToString,
            translation__pb2.TranslateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TranslateMultiple(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/translation.TranslationService/TranslateMultiple',
            translation__pb2.TranslateMultipleRequest.SerializeToString,
            translation__pb2.TranslateMultipleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DetectLanguage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/translation.TranslationService/DetectLanguage',
            translation__pb2.DetectLanguageRequest.SerializeToString,
            translation__pb2.DetectLanguageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSupportedLanguages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/translation.TranslationService/GetSupportedLanguages',
            translation__pb2.SupportedLanguagesRequest.SerializeToString,
            translation__pb2.SupportedLanguagesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetServiceStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/translation.TranslationService/GetServiceStats',
            translation__pb2.ServiceStatsRequest.SerializeToString,
            translation__pb2.ServiceStatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class HealthCheckStub(object):
    """Service de vérification de santé
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Check = channel.unary_unary(
                '/translation.HealthCheck/Check',
                request_serializer=translation__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=translation__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class HealthCheckServicer(object):
    """Service de vérification de santé
    """

    def Check(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HealthCheckServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Check': grpc.unary_unary_rpc_method_handler(
                    servicer.Check,
                    request_deserializer=translation__pb2.HealthCheckRequest.FromString,
                    response_serializer=translation__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'translation.HealthCheck', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('translation.HealthCheck', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class HealthCheck(object):
    """Service de vérification de santé
    """

    @staticmethod
    def Check(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/translation.HealthCheck/Check',
            translation__pb2.HealthCheckRequest.SerializeToString,
            translation__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
