/**
 * DMA Interoperability Adapter
 *
 * Main entry point for WhatsApp EU DMA Interoperability.
 * Replaces the old WhatsAppDMAAdapter with true XMPP-based federation.
 *
 * Status: Phase 2 Development (Ready to start immediately)
 * Can be developed in parallel with Meta application process
 */

import { IProtocolAdapter, ProtocolAdapterConfig, ProtocolMessage } from '../adapters/ProtocolAdapter';
import { XMPPClient } from './xmpp/XMPPClient';
import { SignalProtocolEngine } from './signal-protocol/SignalProtocolEngine';
import { EnlistmentAPIServer } from './enlistment-api/EnlistmentAPIServer';
import { MessageRouter } from './message-router/MessageRouter';
import { PrismaClient } from '../../shared/prisma/client';

/**
 * DMA Interoperability Configuration
 * These will be provided by Meta after application approval
 */
export interface DMAConfig extends ProtocolAdapterConfig {
  // XMPP Server details (from Meta DMA program)
  xmppServer: string; // e.g., "dma.whatsapp.com"
  xmppPort: number; // Usually 5281 for WSS
  xmppVersion: string; // e.g., "1.0"

  // Meeshy Service Details
  meeshyDomain: string; // e.g., "meeshy.app"
  meeshyServiceName: string; // e.g., "Meeshy Messaging Service"

  // Credentials (XMPP authentication)
  meeshyJID: string; // e.g., "meeshy@meeshy.dma.example.com"
  meeshyPassword: string; // OAuth token from Meta

  // Enlistment API (will be exposed by Meeshy)
  enlistmentAPIPort: number;
  enlistmentAPISecret: string;

  // Signal Protocol keys (generated by Meeshy)
  signalPrivateKeyPath?: string; // Path to stored Signal identity key
  signalPublicKeyPath?: string;

  // Optional: Meta-provided test vectors
  testVectorsPath?: string;
}

/**
 * Main DMA Interoperability Adapter
 *
 * Orchestrates:
 * 1. XMPP Client (connection to WhatsApp DMA server)
 * 2. Signal Protocol Engine (E2EE encryption)
 * 3. Enlistment API Server (user verification)
 * 4. Message Router (routing between systems)
 */
export class DMAInteroperabilityAdapter implements IProtocolAdapter {
  readonly protocol = 'whatsapp-dma-interop';

  private config?: DMAConfig;
  private initialized = false;

  // Core components
  private xmppClient?: XMPPClient;
  private signalEngine?: SignalProtocolEngine;
  private enlistmentAPI?: EnlistmentAPIServer;
  private messageRouter?: MessageRouter;

  // Database
  private prisma: PrismaClient;

  constructor(prisma: PrismaClient) {
    this.prisma = prisma;
  }

  /**
   * Configure DMA adapter with Meta-provided credentials
   *
   * This is called after Meta approves the application and provides:
   * - XMPP server details
   * - OAuth tokens
   * - Service configuration
   */
  async configure(config: ProtocolAdapterConfig): Promise<void> {
    const dmaConfig = config as DMAConfig;

    // Validate required fields
    if (!dmaConfig.xmppServer || !dmaConfig.meeshyJID || !dmaConfig.meeshyPassword) {
      throw new Error(
        'DMA requires: xmppServer, meeshyJID, meeshyPassword (from Meta after approval)'
      );
    }

    this.config = dmaConfig;

    // Initialize components
    try {
      // 1. Initialize XMPP client (Phase 2, Week 7-8)
      this.xmppClient = new XMPPClient(this.config);
      await this.xmppClient.initialize();

      // 2. Initialize Signal Protocol engine (Phase 2, Week 1-6)
      this.signalEngine = new SignalProtocolEngine(this.prisma);
      await this.signalEngine.initialize();

      // 3. Initialize Enlistment API server (Phase 2, Week 7-8)
      this.enlistmentAPI = new EnlistmentAPIServer(
        this.prisma,
        this.config.enlistmentAPIPort,
        this.config.enlistmentAPISecret
      );
      await this.enlistmentAPI.start();

      // 4. Initialize message router (Phase 2, Week 7-8)
      this.messageRouter = new MessageRouter(
        this.xmppClient,
        this.signalEngine,
        this.prisma
      );

      this.initialized = true;

      console.log('✅ DMA Interoperability Adapter initialized');
      console.log(`   XMPP Server: ${dmaConfig.xmppServer}`);
      console.log(`   Signal Protocol: Ready`);
      console.log(`   Enlistment API: http://localhost:${dmaConfig.enlistmentAPIPort}`);
    } catch (error) {
      const msg = error instanceof Error ? error.message : 'Unknown error';
      throw new Error(`DMA initialization failed: ${msg}`);
    }
  }

  isConfigured(): boolean {
    return this.initialized && !!this.config;
  }

  /**
   * Send message to WhatsApp user via DMA interoperability
   *
   * Flow:
   * 1. Encrypt with Signal Protocol
   * 2. Send via XMPP to WhatsApp DMA server
   * 3. WhatsApp delivers to recipient
   */
  async sendMessage(message: ProtocolMessage): Promise<{
    success: boolean;
    messageId?: string;
    externalMessageId?: string;
    error?: string;
    errorCode?: string;
  }> {
    if (!this.isConfigured() || !this.xmppClient || !this.signalEngine) {
      return {
        success: false,
        error: 'DMA adapter not configured',
        errorCode: 'NOT_CONFIGURED'
      };
    }

    try {
      // Route through message router
      const result = await this.messageRouter!.routeOutgoing(message);
      return result;
    } catch (error) {
      const msg = error instanceof Error ? error.message : 'Unknown error';
      return {
        success: false,
        error: msg,
        errorCode: 'SEND_FAILED'
      };
    }
  }

  /**
   * Send multiple messages
   */
  async sendBulkMessages(messages: ProtocolMessage[]): Promise<
    Array<{
      success: boolean;
      messageId?: string;
      externalMessageId?: string;
      error?: string;
      errorCode?: string;
    }>
  > {
    return Promise.all(messages.map(msg => this.sendMessage(msg)));
  }

  /**
   * Process incoming webhook from XMPP (wrapped in HTTP by Message Router)
   *
   * Messages come from WhatsApp DMA server via XMPP
   */
  async processIncomingWebhook(payload: Record<string, any>): Promise<ProtocolMessage | null> {
    if (!this.messageRouter) {
      return null;
    }

    try {
      return await this.messageRouter.routeIncoming(payload);
    } catch (error) {
      console.error('Failed to process incoming webhook:', error);
      return null;
    }
  }

  async verifyConnection(): Promise<boolean> {
    if (!this.xmppClient) {
      return false;
    }

    try {
      const isConnected = await this.xmppClient.isConnected();
      console.log(`XMPP Connection Status: ${isConnected ? 'Connected' : 'Disconnected'}`);
      return isConnected;
    } catch (error) {
      console.error('Failed to verify XMPP connection:', error);
      return false;
    }
  }

  async disconnect(): Promise<void> {
    if (this.xmppClient) {
      await this.xmppClient.disconnect();
    }
    if (this.enlistmentAPI) {
      await this.enlistmentAPI.stop();
    }

    this.config = undefined;
    this.initialized = false;
  }

  async getMessageStatus(externalMessageId: string): Promise<{
    status: 'pending' | 'sent' | 'delivered' | 'read' | 'failed';
    updatedAt: Date;
    metadata?: Record<string, any>;
  } | null> {
    // Will be tracked via XMPP message receipts from WhatsApp
    if (!this.messageRouter) {
      return null;
    }

    return this.messageRouter.getMessageStatus(externalMessageId);
  }

  supportsEncryption(): boolean {
    return true; // Signal Protocol is mandatory for DMA
  }

  getEncryptionType(): string | null {
    return 'signal-protocol-dma'; // Mandatory Signal Protocol
  }

  async getRateLimit(): Promise<{
    remaining: number;
    total: number;
    resetAt: Date;
  } | null> {
    // Will be enforced at Enlistment API level
    // Suggest: 100 messages/sec per user
    return {
      remaining: 100,
      total: 100,
      resetAt: new Date(Date.now() + 1000)
    };
  }

  // ===== DMA-Specific Methods =====

  /**
   * Get XMPP connection details (for debugging)
   */
  getXMPPStatus(): {
    connected: boolean;
    jid?: string;
    server?: string;
    uptime?: number;
  } {
    if (!this.xmppClient) {
      return { connected: false };
    }

    return this.xmppClient.getStatus();
  }

  /**
   * Get Signal Protocol statistics
   */
  async getSignalStats(): Promise<{
    sessionsActive: number;
    keysGenerated: number;
    messagesEncrypted: number;
    messagesDecrypted: number;
  } | null> {
    if (!this.signalEngine) {
      return null;
    }

    return this.signalEngine.getStatistics();
  }

  /**
   * Get Enlistment API health
   */
  getEnlistmentAPIHealth(): {
    running: boolean;
    port?: number;
    registrationsProcessed?: number;
  } {
    if (!this.enlistmentAPI) {
      return { running: false };
    }

    return this.enlistmentAPI.getHealth();
  }

  /**
   * Test with Meta's test vectors (after approval)
   * Used during Phase 3 testing
   */
  async runMetaTestVectors(testVectorsPath: string): Promise<{
    passed: number;
    failed: number;
    errors: string[];
  }> {
    if (!this.signalEngine) {
      return {
        passed: 0,
        failed: 0,
        errors: ['Signal engine not initialized']
      };
    }

    try {
      return await this.signalEngine.validateTestVectors(testVectorsPath);
    } catch (error) {
      const msg = error instanceof Error ? error.message : 'Unknown error';
      return {
        passed: 0,
        failed: 1,
        errors: [msg]
      };
    }
  }
}

/**
 * Export for use in ProtocolAdapterManager
 *
 * Will be registered in ProtocolAdapterManager after testing
 */
export function createDMAAdapter(prisma: PrismaClient): IProtocolAdapter {
  return new DMAInteroperabilityAdapter(prisma);
}
