#!/bin/bash

# Database Configuration Script for Meeshy
# This script configures Meeshy to use MongoDB or PostgreSQL

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Default values
DEFAULT_DATABASE_TYPE="MONGODB"
DEFAULT_MONGODB_IMAGE="mongo:8.0"
DEFAULT_POSTGRESQL_IMAGE="postgres:15-alpine"

# Function to print colored output
print_status() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

print_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

print_header() {
    echo -e "${BLUE}=== $1 ===${NC}"
}

# Function to show help
show_help() {
    echo "Usage: $0 [OPTIONS]"
    echo ""
    echo "Options:"
    echo "  -t, --type TYPE       Database type: MONGODB or POSTGRESQL (default: MONGODB)"
    echo "  -i, --image IMAGE     Custom database image"
    echo "  -e, --env ENV         Environment: dev or prod (default: dev)"
    echo "  -h, --help            Show this help message"
    echo ""
    echo "Examples:"
    echo "  $0                    # Use MongoDB 8.0 for development"
    echo "  $0 -t POSTGRESQL      # Use PostgreSQL 15 for development"
    echo "  $0 -t MONGODB -i mongo:7.0 -e prod  # Use MongoDB 7.0 for production"
    echo "  $0 -t POSTGRESQL -i postgres:16 -e prod  # Use PostgreSQL 16 for production"
    echo ""
    echo "Environment Variables:"
    echo "  DATABASE_TYPE         Database type (MONGODB or POSTGRESQL)"
    echo "  DATABASE_IMAGE        Custom database image"
    echo "  ENVIRONMENT           Environment (dev or prod)"
}

# Function to validate database type
validate_database_type() {
    local db_type="$1"
    case "$db_type" in
        MONGODB|POSTGRESQL)
            return 0
            ;;
        *)
            print_error "Invalid database type: $db_type"
            print_error "Valid types: MONGODB, POSTGRESQL"
            return 1
            ;;
    esac
}

# Function to get database image
get_database_image() {
    local db_type="$1"
    local custom_image="$2"
    
    if [ -n "$custom_image" ]; then
        echo "$custom_image"
    else
        case "$db_type" in
            MONGODB)
                echo "$DEFAULT_MONGODB_IMAGE"
                ;;
            POSTGRESQL)
                echo "$DEFAULT_POSTGRESQL_IMAGE"
                ;;
        esac
    fi
}

# Function to create environment file
create_env_file() {
    local db_type="$1"
    local db_image="$2"
    local env="$3"
    
    local env_file=".env.database"
    
    print_status "Creating database environment file: $env_file"
    
    cat > "$env_file" << EOF
# Database Configuration for Meeshy
# Generated by configure-database.sh

# Environment
ENVIRONMENT=$env

# Database Type
DATABASE_TYPE=$db_type

# Database Image
DATABASE_IMAGE=$db_image

EOF
    
    if [ "$db_type" = "MONGODB" ]; then
        cat >> "$env_file" << EOF
# MongoDB Configuration
MONGODB_URL=mongodb://meeshy:MeeshyPassword123@database:27017/meeshy?authSource=admin
MONGODB_DATABASE=meeshy
MONGODB_USER=meeshy
MONGODB_PASSWORD=MeeshyPassword123

# Prisma Configuration (MongoDB)
DATABASE_URL=\$MONGODB_URL
PRISMA_SCHEMA_PATH=./shared/schema.prisma
EOF
    else
        cat >> "$env_file" << EOF
# PostgreSQL Configuration
POSTGRESQL_URL=postgresql://meeshy:MeeshyPassword123@database:5432/meeshy
POSTGRESQL_DATABASE=meeshy
POSTGRESQL_USER=meeshy
POSTGRESQL_PASSWORD=MeeshyPassword123
POSTGRESQL_HOST=database
POSTGRESQL_PORT=5432

# Prisma Configuration (PostgreSQL)
DATABASE_URL=\$POSTGRESQL_URL
PRISMA_SCHEMA_PATH=./shared/schema.postgresql.prisma
EOF
    fi
    
    cat >> "$env_file" << EOF

# Docker Compose File
DOCKER_COMPOSE_FILE=docker-compose.$env.yml
EOF
    
    print_status "Environment file created: $env_file"
}

# Function to create docker-compose symlink
create_docker_compose_symlink() {
    local env="$1"
    
    local compose_file="docker-compose.yml"
    local target_file="docker-compose.$env.yml"
    
    if [ -f "$target_file" ]; then
        print_status "Creating symlink: $compose_file -> $target_file"
        
        # Remove existing symlink or file
        rm -f "$compose_file"
        
        # Create symlink
        ln -sf "$target_file" "$compose_file"
        
        print_status "Symlink created successfully"
    else
        print_error "Target file not found: $target_file"
        exit 1
    fi
}

# Function to show configuration summary
show_summary() {
    local db_type="$1"
    local db_image="$2"
    local env="$3"
    
    print_header "Database Configuration Summary"
    echo "Environment: $env"
    echo "Database Type: $db_type"
    echo "Database Image: $db_image"
    echo ""
    
    case "$db_type" in
        MONGODB)
            echo "MongoDB Configuration:"
            echo "  - Port: 27017"
            echo "  - Database: meeshy"
            echo "  - User: meeshy"
            echo "  - Password: MeeshyPassword123"
            echo "  - Schema: ./shared/schema.prisma"
            echo "  - Prisma Variable: DATABASE_URL"
            ;;
        POSTGRESQL)
            echo "PostgreSQL Configuration:"
            echo "  - Port: 5432"
            echo "  - Database: meeshy"
            echo "  - User: meeshy"
            echo "  - Password: MeeshyPassword123"
            echo "  - Schema: ./shared/schema.postgresql.prisma"
            echo "  - Prisma Variable: DATABASE_URL"
            ;;
    esac
    
    echo ""
    echo "Files created/updated:"
    echo "  - .env.database (database configuration)"
    echo "  - docker-compose.yml -> docker-compose.$env.yml (symlink)"
    echo ""
    
    echo "Docker Compose Files:"
    echo "  - docker-compose.dev.yml (development)"
    echo "  - docker-compose.prod.yml (production)"
    echo ""
    
    echo "Next steps:"
    echo "  1. Review the configuration in .env.database"
    echo "  2. Start services: docker-compose up -d"
    echo "  3. Check logs: docker-compose logs -f"
    echo ""
    echo "Environment-specific commands:"
    if [ "$env" = "dev" ]; then
        echo "  - Development: docker-compose -f docker-compose.dev.yml up -d"
        echo "  - Production: docker-compose -f docker-compose.prod.yml up -d"
    else
        echo "  - Development: docker-compose -f docker-compose.dev.yml up -d"
        echo "  - Production: docker-compose -f docker-compose.prod.yml up -d"
    fi
}

# Main script
main() {
    local database_type="$DEFAULT_DATABASE_TYPE"
    local database_image=""
    local environment="$ENVIRONMENT"
    
    # Parse command line arguments
    while [[ $# -gt 0 ]]; do
        case $1 in
            -t|--type)
                database_type="$2"
                shift 2
                ;;
            -i|--image)
                database_image="$2"
                shift 2
                ;;
            -e|--env)
                environment="$2"
                shift 2
                ;;
            -h|--help)
                show_help
                exit 0
                ;;
            *)
                print_error "Unknown option: $1"
                show_help
                exit 1
                ;;
        esac
    done
    
    # Check if environment variables override defaults
    if [ -n "$DATABASE_TYPE" ]; then
        database_type="$DATABASE_TYPE"
    fi
    
    if [ -n "$DATABASE_IMAGE" ]; then
        database_image="$DATABASE_IMAGE"
    fi
    
    if [ -n "$ENVIRONMENT" ]; then
        environment="$ENVIRONMENT"
    fi
    
    # Validate database type
    if ! validate_database_type "$database_type"; then
        exit 1
    fi
    
    # Validate environment
    case "$environment" in
        dev|prod)
            ;;
        *)
            print_error "Invalid environment: $environment"
            print_error "Valid environments: dev, prod"
            exit 1
            ;;
    esac
    
    # Get database image
    database_image=$(get_database_image "$database_type" "$database_image")
    
    print_header "Configuring Meeshy Database"
    print_status "Environment: $environment"
    print_status "Database Type: $database_type"
    print_status "Database Image: $database_image"
    echo ""
    
    # Create environment file
    create_env_file "$database_type" "$database_image" "$environment"
    
    # Create docker-compose symlink
    create_docker_compose_symlink "$environment"
    
    # Show summary
    show_summary "$database_type" "$database_image" "$environment"
    
    print_status "Database configuration completed successfully!"
}

# Run main function
main "$@"
