export const USER_SELECT_FIELDS = {
  id: true,
  username: true,
  firstName: true,
  lastName: true,
  displayName: true,
  email: true,
  phoneNumber: true,
  systemLanguage: true,
  regionalLanguage: true,
  customDestinationLanguage: true,
  autoTranslateEnabled: true,
  translateToSystemLanguage: true,
  translateToRegionalLanguage: true,
  useCustomDestination: true,
  avatar: true,
  isOnline: true,
  lastSeen: true,
  createdAt: true,
  lastActiveAt: true,
} as const;

export const USER_BASIC_SELECT_FIELDS = {
  id: true,
  username: true,
  firstName: true,
  lastName: true,
  displayName: true,
  avatar: true,
  isOnline: true,
  systemLanguage: true,
  regionalLanguage: true,
  customDestinationLanguage: true,
} as const;
